{{- if .Values.repos }}
{{- $top := . -}}
{{- range $index, $repo := .Values.repos }}
{{- if $repo.url }}
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ $top.Values.name }}
spec:
  generators:
  - git:
      repoURL: {{ $repo.url }}
      revision: main
      directories:
      - path: {{ $repo.path }}
  template:
    metadata:
      name: {{ $top.Values.name }}
    spec:
      project: {{ $top.Values.project }}
      source:
        repoURL: {{ $repo.url }}
        targetRevision: main
        path: '{{`{{path}}`}}'
      destination:
        server: 'kubernetes.svc'
        namespace: argocd # '{{ `{{path.basename}}` }}' # defined by application
{{- end }}
{{- end }}
{{- end }}
